const LUMA_UI_VERSION='0.8.0';
const LUMA_SHELL_VERSION='1.0.1';
const nav=[...document.querySelectorAll('.bottom-nav [data-go]')];
function go(target){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===target));nav.forEach(b=>b.classList.toggle('active',b.dataset.go===target));window.scrollTo(0,0);}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
function updateClock(){const el=document.getElementById('clock');if(el)el.textContent=new Date().toLocaleTimeString('de-CH',{hour:'2-digit',minute:'2-digit'});}updateClock();setInterval(updateClock,30000);

const librarySearch=document.getElementById('librarySearch');
const libraryDocs=[...document.querySelectorAll('.library-doc')];
const libraryTabs=[...document.querySelectorAll('[data-library-tab]')];
const categoryButtons=[...document.querySelectorAll('[data-library-category]')];
const libraryResultCount=document.getElementById('libraryResultCount');
const libraryListTitle=document.getElementById('libraryListTitle');
const libraryEmpty=document.getElementById('libraryEmpty');
let activeLibraryTab='all';let activeLibraryCategory='all';
function renderLibrary(){const q=(librarySearch?.value||'').trim().toLocaleLowerCase('de-CH');let visible=0;libraryDocs.forEach(doc=>{const title=(doc.dataset.title||'').toLocaleLowerCase('de-CH');const matchesSearch=!q||title.includes(q);const matchesCategory=activeLibraryCategory==='all'||doc.dataset.category===activeLibraryCategory;const matchesTab=activeLibraryTab==='all'||doc.dataset[activeLibraryTab]==='true';const show=matchesSearch&&matchesCategory&&matchesTab;doc.hidden=!show;if(show)visible++;});if(libraryResultCount)libraryResultCount.textContent=`${visible} angezeigt`;if(libraryEmpty)libraryEmpty.hidden=visible!==0;}
librarySearch?.addEventListener('input',renderLibrary);
libraryTabs.forEach(tab=>tab.addEventListener('click',()=>{activeLibraryTab=tab.dataset.libraryTab;libraryTabs.forEach(t=>t.classList.toggle('active',t===tab));const titles={all:'ALLE DOKUMENTE',recent:'ZULETZT GEÖFFNET',favorites:'FAVORITEN',offline:'OFFLINE VERFÜGBAR'};if(libraryListTitle)libraryListTitle.textContent=titles[activeLibraryTab]||'ALLE DOKUMENTE';renderLibrary();}));
categoryButtons.forEach(button=>button.addEventListener('click',()=>{const category=button.dataset.libraryCategory;activeLibraryCategory=activeLibraryCategory===category?'all':category;categoryButtons.forEach(b=>b.classList.toggle('selected',b.dataset.libraryCategory===activeLibraryCategory));renderLibrary();}));
document.querySelectorAll('.view-switch button').forEach(button=>button.addEventListener('click',()=>{button.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));button.classList.add('selected');}));
renderLibrary();

const readerData={'SIA 382/1 – Lüftungs- und Klimaanlagen':{page:132,pages:356,section:'Lüftung und Luftqualität'},'SIA 181 – Schallschutz im Hochbau':{page:18,pages:96,section:'Anforderungen und Beurteilung'},'Eurocode 3':{page:76,pages:214,section:'Verbindungsmittel'},'Building Physics':{page:205,pages:336,section:'Heat, Air and Moisture'},'Advanced Python Programming':{page:45,pages:168,section:'Functions and Data Structures'},'BOOX Tab Ultra C Pro – User Guide':{page:12,pages:84,section:'Display and E-Ink Settings'},'Revit MEP Best Practices':{page:31,pages:240,section:'Model Coordination'},'Lüftungskonzept MFH – Ausführung':{page:27,pages:82,section:'Luftführung und Ausführung'}};
let activeReaderDoc='SIA 382/1 – Lüftungs- und Klimaanlagen';let readerPage=132;
function loadReader(title){activeReaderDoc=title||activeReaderDoc;const data=readerData[activeReaderDoc]||{page:1,pages:100,section:'Document'};readerPage=data.page;document.getElementById('readerDocTitle').textContent=activeReaderDoc;document.getElementById('readerPage').textContent=readerPage;document.getElementById('readerPages').textContent=data.pages;document.getElementById('readerSectionTitle').textContent=data.section;go('reader');}
document.querySelectorAll('.open-reader').forEach(b=>b.addEventListener('click',()=>loadReader(b.dataset.doc)));
document.getElementById('readerPrev')?.addEventListener('click',()=>{readerPage=Math.max(1,readerPage-1);document.getElementById('readerPage').textContent=readerPage;});
document.getElementById('readerNext')?.addEventListener('click',()=>{const max=Number(document.getElementById('readerPages').textContent)||999;readerPage=Math.min(max,readerPage+1);document.getElementById('readerPage').textContent=readerPage;});
document.querySelectorAll('[data-reader-tool]').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('selected');if(b.dataset.readerTool==='bookmark')b.textContent=b.classList.contains('selected')?'★ Bookmarked':'☆ Bookmark';}));

const projectCards=[...document.querySelectorAll('.project-card')];
function selectProject(card){projectCards.forEach(c=>c.classList.toggle('selected',c===card));document.getElementById('projectTitle').textContent=card.dataset.project;document.getElementById('projectProgress').textContent=`${card.dataset.progress}%`;document.getElementById('projectTasks').textContent=card.dataset.tasks;document.getElementById('projectProgressBar').style.width=`${card.dataset.progress}%`;}
projectCards.forEach(card=>card.addEventListener('click',()=>selectProject(card)));
document.querySelectorAll('[data-work-tab]').forEach(tab=>tab.addEventListener('click',()=>{tab.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));tab.classList.add('active');}));

const noteCards=[...document.querySelectorAll('.note-card')];
function selectNote(card){noteCards.forEach(c=>c.classList.toggle('selected',c===card));document.getElementById('noteTitle').value=card.dataset.note;document.getElementById('noteDate').textContent=card.dataset.date;}
noteCards.forEach(card=>card.addEventListener('click',()=>selectNote(card)));
document.querySelectorAll('.open-note').forEach(b=>b.addEventListener('click',()=>{const card=noteCards.find(c=>c.dataset.note===b.dataset.note);if(card)selectNote(card);go('notes');}));
document.querySelectorAll('.note-tools button').forEach(b=>b.addEventListener('click',()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');}));
document.getElementById('newNote')?.addEventListener('click',()=>{document.getElementById('noteTitle').value='Neue Notiz';document.getElementById('noteDate').textContent=new Date().toLocaleDateString('de-CH');noteCards.forEach(c=>c.classList.remove('selected'));});

const modeButtons=[...document.querySelectorAll('.mode-switch button')];modeButtons.forEach(b=>b.addEventListener('click',()=>{modeButtons.forEach(x=>x.classList.remove('selected'));b.classList.add('selected');}));
let aiContext='general';
function setAiContext(context){aiContext=context;const labels={general:'General workspace',reader:`Document: ${activeReaderDoc}`,project:`Project: ${document.getElementById('projectTitle')?.textContent||'Active project'}`,notes:`Note: ${document.getElementById('noteTitle')?.value||'Selected note'}`};document.getElementById('aiContextLabel').textContent=`Context: ${labels[context]}`;document.querySelectorAll('[data-ai-context]').forEach(b=>b.classList.toggle('selected',b.dataset.aiContext===context));}
document.querySelectorAll('[data-ai-context]').forEach(b=>b.addEventListener('click',()=>setAiContext(b.dataset.aiContext)));
document.querySelectorAll('.ask-ai').forEach(b=>b.addEventListener('click',()=>{setAiContext(b.dataset.context||'general');go('ai');}));
function addMessage(className,text){const chat=document.getElementById('chatCard');const box=document.createElement('div');box.className=`message ${className}`;const p=document.createElement('p');p.textContent=text;box.appendChild(p);chat.appendChild(box);}
function sendAi(text){const input=document.getElementById('aiInput');const value=(text||input?.value||'').trim();if(!value)return;addMessage('user',value);const contextText={general:'dem LuMa Workspace',reader:`dem geöffneten Dokument ${activeReaderDoc}`,project:`dem aktiven Projekt ${document.getElementById('projectTitle')?.textContent}`,notes:`der ausgewählten Notiz ${document.getElementById('noteTitle')?.value}`}[aiContext];addMessage('assistant',`Kontext aus ${contextText} ist aktiv. Die Benutzeroberfläche ist bereits vollständig verbunden; die echte Modellantwort folgt mit dem LuMa-AI-Backend.`);if(input)input.value='';}
document.getElementById('aiSend')?.addEventListener('click',()=>sendAi());
document.getElementById('aiInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')sendAi();});
document.querySelectorAll('.ai-suggestions button').forEach(b=>b.addEventListener('click',()=>sendAi(b.textContent)));

function nativeUiVersion(){try{return window.LuMaNative?.getUiVersion?.()||LUMA_UI_VERSION;}catch(e){return LUMA_UI_VERSION;}}
function nativeShellVersion(){try{return window.LuMaNative?.getShellVersion?.()||LUMA_SHELL_VERSION;}catch(e){return LUMA_SHELL_VERSION;}}
function parseNative(method,fallback={}){try{const value=window.LuMaNative?.[method]?.();return value?JSON.parse(value):fallback;}catch(e){return fallback;}}
function formatBytes(bytes){if(!Number.isFinite(Number(bytes))||Number(bytes)<0)return '—';const gb=Number(bytes)/1073741824;return `${gb>=10?gb.toFixed(0):gb.toFixed(1)} GB`;}

function injectUpdaterStyle(){if(document.getElementById('lumaUpdaterStyle'))return;const style=document.createElement('style');style.id='lumaUpdaterStyle';style.textContent='.luma-version-badge{position:fixed;right:12px;top:118px;z-index:20;font-size:11px;font-weight:700;color:#39484a;background:#fff;border:2px solid #8f9b99;padding:5px 8px}.luma-update-toast{position:fixed;z-index:60;left:50%;transform:translateX(-50%);bottom:116px;width:min(calc(100vw - 32px),700px);border:2px solid #07565b;background:#fff;padding:14px 18px;font-weight:700;text-align:center}@media(max-width:720px){.luma-version-badge{top:94px}}';document.head.appendChild(style);}
function showVersionBadge(){injectUpdaterStyle();document.querySelectorAll('.luma-version-badge').forEach(x=>x.remove());const badge=document.createElement('div');badge.className='luma-version-badge';badge.textContent=`UI ${nativeUiVersion()} · Shell ${nativeShellVersion()}`;document.body.appendChild(badge);}
function showUpdateToast(text){injectUpdaterStyle();const old=document.querySelector('.luma-update-toast');if(old)old.remove();const toast=document.createElement('div');toast.className='luma-update-toast';toast.textContent=text;document.body.appendChild(toast);setTimeout(()=>toast.remove(),4500);}

const LUMA_SIGNET='<svg viewBox="0 0 1024 1024" role="img" aria-label="LuMa Labs"><g fill="currentColor"><polygon points="138.250,154.500 229.250,242.250 229.250,785.000 473.000,785.000 554.250,869.500 138.250,869.500"/><polygon points="333.250,356.000 557.500,573.750 794.750,278.000 882.500,278.000 882.500,869.500 794.750,869.500 794.750,434.000 564.000,668.000 333.250,450.250"/></g></svg>';
function injectFoundationStyles(){if(document.getElementById('lumaFoundationStyle'))return;const s=document.createElement('style');s.id='lumaFoundationStyle';s.textContent=`.brandmark{background:#fff!important;color:#000!important;border:2px solid #071117!important;border-radius:8px!important;padding:7px!important}.brandmark svg{width:100%;height:100%;display:block}.diagnostics-screen{background:#f4f6f8;min-height:calc(100dvh - 104px)}.diagnostics-wrap{padding:40px}.diagnostics-top{display:flex;align-items:flex-end;justify-content:space-between;padding-bottom:24px;border-bottom:2px solid #8a9694}.diagnostics-top h1{font-size:48px;margin:8px 0 0}.diag-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin-top:24px}.diag-card{min-height:126px;background:#fff;border:2px solid #8a9694;border-radius:12px;padding:18px}.diag-card span,.diag-card strong{display:block}.diag-card span{font-size:12px;font-weight:800;letter-spacing:.06em;color:#354547}.diag-card strong{font-size:22px;margin-top:12px}.diag-actions{margin-top:18px;display:grid;grid-template-columns:1fr 1fr;gap:12px}.diag-actions button{min-height:58px;border:2px solid #071117;border-radius:10px;background:#fff;font-weight:800}.diag-actions button.primary-action{background:#071117;color:#fff}.diag-file{margin-top:18px;border:2px solid #8a9694;background:#fff;padding:18px;border-radius:12px}.diag-file small{display:block;margin-top:6px}.native-value{font-variant-numeric:tabular-nums}@media(max-width:720px){.diagnostics-wrap{padding:28px}.diag-grid{grid-template-columns:1fr 1fr}.diagnostics-top h1{font-size:42px}}`;document.head.appendChild(s);}
function applyBranding(){injectFoundationStyles();const mark=document.querySelector('.brandmark');if(mark)mark.innerHTML=LUMA_SIGNET;const subtitle=document.querySelector('.brand-subtitle');if(subtitle)subtitle.textContent='LUMA LABS · ENGINEERING WORKSPACE';}

function ensureDiagnostics(){if(document.querySelector('[data-screen="diagnostics"]'))return;const main=document.querySelector('main.content');if(!main)return;const section=document.createElement('section');section.className='screen diagnostics-screen';section.dataset.screen='diagnostics';section.innerHTML=`<div class="diagnostics-wrap"><div class="diagnostics-top"><div><span class="eyebrow">LUMA SLATE SYSTEM</span><h1>Diagnostics</h1></div><button class="toolbar-button" id="diagBack">‹ Home</button></div><div class="diag-grid"><div class="diag-card"><span>SHELL</span><strong id="diagShell">${nativeShellVersion()}</strong></div><div class="diag-card"><span>UI</span><strong id="diagUi">${nativeUiVersion()}</strong></div><div class="diag-card"><span>BATTERY</span><strong id="diagBattery">—</strong></div><div class="diag-card"><span>STORAGE FREE</span><strong id="diagStorage">—</strong></div><div class="diag-card"><span>NETWORK</span><strong id="diagNetwork">—</strong></div><div class="diag-card"><span>UPDATE</span><strong id="diagUpdate">—</strong></div><div class="diag-card"><span>DEVICE</span><strong id="diagDevice">—</strong></div><div class="diag-card"><span>CHANNEL</span><strong id="diagChannel">stable</strong></div></div><div class="diag-actions"><button class="primary-action" id="diagCheckUpdate">Nach Updates suchen</button><button id="diagOpenFile">Dokument öffnen</button></div><div class="diag-file"><strong>Letzte Dateiauswahl</strong><small id="diagFile">Noch kein Dokument ausgewählt.</small></div></div>`;main.appendChild(section);
document.getElementById('diagBack')?.addEventListener('click',()=>go('home'));
document.getElementById('diagCheckUpdate')?.addEventListener('click',()=>{showUpdateToast('Suche nach Updates …');try{window.LuMaNative?.checkForUpdates?.();}catch(e){showUpdateToast('Native Update-Funktion ist in dieser Shell noch nicht verfügbar.');}});
document.getElementById('diagOpenFile')?.addEventListener('click',()=>openNativeFilePicker());
const tools=[...document.querySelectorAll('.tile')].find(t=>t.querySelector('strong')?.textContent.trim()==='TOOLS');if(tools){tools.addEventListener('click',()=>{refreshNativeData();go('diagnostics');});tools.querySelector('small').textContent='System & diagnostics';}
const fileQuick=[...document.querySelectorAll('.quick-grid button')].find(b=>b.querySelector('span')?.textContent.trim()==='Files');fileQuick?.addEventListener('click',openNativeFilePicker);
}
function openNativeFilePicker(){if(window.LuMaNative?.pickDocument){window.LuMaNative.pickDocument();}else{showUpdateToast('Dateiauswahl benötigt Shell 1.0.1.');}}
function refreshNativeData(){const sys=parseNative('getSystemInfo',{});const upd=parseNative('getUpdateStatus',{});const statusSpans=[...document.querySelectorAll('.topbar .status span')];if(statusSpans[0]&&sys.networkType)statusSpans[0].textContent=sys.networkType;if(statusSpans[1]&&Number.isFinite(sys.batteryPercent))statusSpans[1].textContent=`${sys.batteryPercent}%`;const heroMeta=document.querySelectorAll('.hero-meta>div');if(heroMeta[1]&&Number.isFinite(sys.batteryPercent)){heroMeta[1].querySelector('strong').textContent=`${sys.batteryPercent}%`;heroMeta[1].querySelector('span').textContent=sys.charging?'Charging':'Battery';}if(heroMeta[2]&&sys.storageFreeBytes){heroMeta[2].querySelector('strong').textContent=formatBytes(sys.storageFreeBytes);heroMeta[2].querySelector('span').textContent='Free';}const set=(id,value)=>{const el=document.getElementById(id);if(el&&value!==undefined&&value!==null&&value!=='')el.textContent=value;};set('diagShell',nativeShellVersion());set('diagUi',nativeUiVersion());set('diagBattery',Number.isFinite(sys.batteryPercent)?`${sys.batteryPercent}%${sys.charging?' · charging':''}`:'Unavailable');set('diagStorage',sys.storageFreeBytes?formatBytes(sys.storageFreeBytes):'Unavailable');set('diagNetwork',sys.networkType||'Unavailable');set('diagUpdate',upd.status||'idle');set('diagDevice',sys.deviceModel||'BOOX / Android');set('diagChannel',upd.channel||'stable');showVersionBadge();}
window.addEventListener('luma-file-selected',e=>{const d=e.detail||{};const text=[d.name||'Dokument',d.mime||'',d.size?formatBytes(d.size):''].filter(Boolean).join(' · ');const el=document.getElementById('diagFile');if(el)el.textContent=text;showUpdateToast(`${d.name||'Dokument'} ausgewählt.`);});
window.addEventListener('luma-update-status',e=>{const status=e.detail?.status||'unknown';const labels={up_to_date:'LuMa Slate ist aktuell.',shell_required:'Neue Shell-Version erforderlich.',checking:'Update wird geprüft.',downloading:'Update wird geladen.'};showUpdateToast(labels[status]||`Update-Status: ${status}`);refreshNativeData();});
window.addEventListener('luma-update-error',()=>{showUpdateToast('Update konnte nicht geladen werden. WLAN prüfen und erneut versuchen.');refreshNativeData();});

applyBranding();
ensureDiagnostics();
refreshNativeData();
showVersionBadge();
setTimeout(()=>{refreshNativeData();showVersionBadge();},1200);
setInterval(refreshNativeData,60000);
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
