const LUMA_UI_VERSION='0.9.0';
const LUMA_SHELL_VERSION='1.0.1';
const K={docs:'luma.docs.v1',reader:'luma.reader.v1',notes:'luma.notes.v1',chat:'luma.chat.v1'};
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav=[...document.querySelectorAll('.bottom-nav [data-go]')];
function go(t){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===t));nav.forEach(b=>b.classList.toggle('active',b.dataset.go===t));window.scrollTo(0,0)}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
function clock(){const e=document.getElementById('clock');if(e)e.textContent=new Date().toLocaleTimeString('de-CH',{hour:'2-digit',minute:'2-digit'})}clock();setInterval(clock,30000);

function toast(t){let e=document.querySelector('.luma-update-toast');if(e)e.remove();e=document.createElement('div');e.className='luma-update-toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),4200)}
function nativeVer(m,f){try{return window.LuMaNative?.[m]?.()||f}catch{return f}}
function parseNative(m){try{return JSON.parse(window.LuMaNative?.[m]?.()||'{}')}catch{return {}}}
function fmt(b){if(!Number.isFinite(Number(b)))return '—';const g=Number(b)/1073741824;return `${g>=10?g.toFixed(0):g.toFixed(1)} GB`}
function pick(){if(window.LuMaNative?.pickDocument)window.LuMaNative.pickDocument();else toast('Dateiauswahl benötigt Shell 1.0.1.')}

const SIGNET='<svg viewBox="0 0 1024 1024" aria-label="LuMa Labs"><g fill="currentColor"><polygon points="138.250,154.500 229.250,242.250 229.250,785.000 473.000,785.000 554.250,869.500 138.250,869.500"/><polygon points="333.250,356.000 557.500,573.750 794.750,278.000 882.500,278.000 882.500,869.500 794.750,869.500 794.750,434.000 564.000,668.000 333.250,450.250"/></g></svg>';
function styles(){if(document.getElementById('luma-v09'))return;const s=document.createElement('style');s.id='luma-v09';s.textContent=`.brandmark{background:#fff!important;color:#000!important;border:2px solid #071117!important;border-radius:8px!important;padding:7px!important}.brandmark svg{width:100%;height:100%;display:block}.luma-update-toast{position:fixed;z-index:80;left:50%;transform:translateX(-50%);bottom:116px;width:min(calc(100vw - 32px),700px);border:2px solid #07565b;background:#fff;padding:14px 18px;font-weight:800;text-align:center}.luma-version-badge{position:fixed;right:12px;top:118px;z-index:20;font-size:11px;font-weight:800;background:#fff;border:2px solid #8f9b99;padding:5px 8px}.luma-blockbar{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}.luma-btn{min-height:52px;border:2px solid #071117;background:#fff;border-radius:10px;font-weight:800;padding:10px 14px}.luma-btn.primary{background:#071117;color:#fff}.luma-card{border:2px solid #8f9b99;background:#fff;padding:14px;border-radius:10px;margin:12px 0}.luma-card strong,.luma-card small{display:block}.luma-card small{margin-top:5px;color:#39484a}.imported-doc{display:grid!important;grid-template-columns:1fr auto!important;gap:12px!important}.luma-fav{min-width:48px;min-height:48px;border:2px solid #071117;background:#fff;border-radius:9px;font-size:20px}.luma-mini{height:5px;background:#dfe9e6;margin-top:8px}.luma-mini i{display:block;height:100%;background:#071117}.luma-notes-list{display:grid;gap:8px;margin:12px 0}.luma-note-item{border:2px solid #8f9b99;background:#fff;border-radius:10px;padding:12px;text-align:left}.luma-note-item.selected{border-color:#071117;border-width:3px}.luma-note-editor{width:100%;min-height:190px;border:2px solid #8f9b99;border-radius:10px;padding:14px;background:#fff;color:#071719;font:inherit;resize:none}.diag-wrap{padding:36px}.diag-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.diag{border:2px solid #8f9b99;background:#fff;border-radius:10px;padding:14px}.diag span,.diag strong{display:block}.diag strong{margin-top:8px;font-size:20px}@media(max-width:720px){.diag-wrap{padding:26px}.luma-version-badge{top:94px}}`;document.head.appendChild(s)}
function brand(){styles();const m=document.querySelector('.brandmark');if(m)m.innerHTML=SIGNET;const s=document.querySelector('.brand-subtitle');if(s)s.textContent='LUMA LABS · ENGINEERING WORKSPACE'}
function badge(){document.querySelectorAll('.luma-version-badge').forEach(x=>x.remove());const e=document.createElement('div');e.className='luma-version-badge';e.textContent=`UI ${nativeVer('getUiVersion',LUMA_UI_VERSION)} · Shell ${nativeVer('getShellVersion',LUMA_SHELL_VERSION)}`;document.body.appendChild(e)}

let imported=read(K.docs,[]),rstate=read(K.reader,{}),activeDoc='SIA 382/1 – Lüftungs- und Klimaanlagen',page=132;
const baseDocs={'SIA 382/1 – Lüftungs- und Klimaanlagen':{page:132,pages:356,section:'Lüftung und Luftqualität'},'SIA 181 – Schallschutz im Hochbau':{page:18,pages:96,section:'Anforderungen und Beurteilung'},'Eurocode 3':{page:76,pages:214,section:'Verbindungsmittel'},'Building Physics':{page:205,pages:336,section:'Heat, Air and Moisture'},'Advanced Python Programming':{page:45,pages:168,section:'Functions and Data Structures'},'BOOX Tab Ultra C Pro – User Guide':{page:12,pages:84,section:'Display and E-Ink Settings'},'Revit MEP Best Practices':{page:31,pages:240,section:'Model Coordination'},'Lüftungskonzept MFH – Ausführung':{page:27,pages:82,section:'Luftführung und Ausführung'}};
function saveReader(){const max=Number(document.getElementById('readerPages')?.textContent)||1,bookmark=document.querySelector('[data-reader-tool="bookmark"]')?.classList.contains('selected')||false;rstate[activeDoc]={...(rstate[activeDoc]||{}),page,pages:max,bookmark,updatedAt:Date.now()};write(K.reader,rstate);const d=imported.find(x=>x.name===activeDoc);if(d){d.page=page;d.pages=max;d.progress=Math.min(100,Math.round(page/max*100));d.lastOpened=Date.now();d.recent=true;write(K.docs,imported)}}
function openReader(t){activeDoc=t||activeDoc;const b=baseDocs[activeDoc]||imported.find(x=>x.name===activeDoc)||{page:1,pages:1,section:'Imported document'},st=rstate[activeDoc]||{};page=st.page||b.page||1;const max=st.pages||b.pages||1;const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('readerDocTitle',activeDoc);set('readerPage',page);set('readerPages',max);set('readerSectionTitle',b.section||'Imported document');const bm=document.querySelector('[data-reader-tool="bookmark"]');if(bm){bm.classList.toggle('selected',!!st.bookmark);bm.textContent=st.bookmark?'★ Bookmarked':'☆ Bookmark'}saveReader();renderImported();go('reader')}
document.querySelectorAll('.open-reader').forEach(b=>b.addEventListener('click',()=>openReader(b.dataset.doc)));
document.getElementById('readerPrev')?.addEventListener('click',()=>{page=Math.max(1,page-1);document.getElementById('readerPage').textContent=page;saveReader();renderImported()});
document.getElementById('readerNext')?.addEventListener('click',()=>{page=Math.min(Number(document.getElementById('readerPages')?.textContent)||999,page+1);document.getElementById('readerPage').textContent=page;saveReader();renderImported()});
document.querySelectorAll('[data-reader-tool]').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('selected');if(b.dataset.readerTool==='bookmark')b.textContent=b.classList.contains('selected')?'★ Bookmarked':'☆ Bookmark';saveReader()}));

const search=document.getElementById('librarySearch'),tabs=[...document.querySelectorAll('[data-library-tab]')],cats=[...document.querySelectorAll('[data-library-category]')];let tab='all',cat='all';
function renderLibrary(){const q=(search?.value||'').trim().toLowerCase();let n=0;document.querySelectorAll('.library-doc').forEach(d=>{const ok=(!q||(d.dataset.title||'').toLowerCase().includes(q))&&(cat==='all'||d.dataset.category===cat)&&(tab==='all'||d.dataset[tab]==='true');d.hidden=!ok;if(ok)n++});const c=document.getElementById('libraryResultCount');if(c)c.textContent=`${n} angezeigt`;const e=document.getElementById('libraryEmpty');if(e)e.hidden=n!==0}
search?.addEventListener('input',renderLibrary);tabs.forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.libraryTab;tabs.forEach(x=>x.classList.toggle('active',x===b));const names={all:'ALLE DOKUMENTE',recent:'ZULETZT GEÖFFNET',favorites:'FAVORITEN',offline:'OFFLINE VERFÜGBAR'};const h=document.getElementById('libraryListTitle');if(h)h.textContent=names[tab];renderLibrary()}));cats.forEach(b=>b.addEventListener('click',()=>{cat=cat===b.dataset.libraryCategory?'all':b.dataset.libraryCategory;cats.forEach(x=>x.classList.toggle('selected',x.dataset.libraryCategory===cat));renderLibrary()}));
function renderImported(){document.querySelectorAll('.library-doc.imported-doc').forEach(x=>x.remove());const host=document.getElementById('libraryDocuments');if(!host)return;[...imported].sort((a,b)=>(b.lastOpened||b.importedAt||0)-(a.lastOpened||a.importedAt||0)).forEach(d=>{const e=document.createElement('div');e.className='library-doc imported-doc';e.dataset.title=d.name;e.dataset.category='personal';e.dataset.recent=String(!!d.recent);e.dataset.favorites=String(!!d.favorite);e.dataset.offline='true';const p=Number(d.progress)||0;e.innerHTML=`<div><span class="file-badge">${(d.mime||'DOC').includes('pdf')?'PDF':'DOC'}</span><div class="doc-copy"><strong>${esc(d.name)}</strong><small>Importiert · ${d.size?fmt(d.size):'lokal'} · ${p}% gelesen</small><span class="luma-mini"><i style="width:${p}%"></i></span></div></div><div><button class="luma-btn primary" data-open="${encodeURIComponent(d.name)}">Reader</button><button class="luma-fav" data-fav="${encodeURIComponent(d.name)}">${d.favorite?'★':'☆'}</button></div>`;host.appendChild(e)});document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openReader(decodeURIComponent(b.dataset.open))));document.querySelectorAll('[data-fav]').forEach(b=>b.addEventListener('click',()=>{const d=imported.find(x=>x.name===decodeURIComponent(b.dataset.fav));if(d){d.favorite=!d.favorite;write(K.docs,imported);renderImported();renderLibrary()}}));renderLibrary()}
function importDoc(d){if(!d?.name)return;const old=imported.find(x=>x.uri===d.uri||x.name===d.name),n={name:d.name,uri:d.uri||old?.uri||'',mime:d.mime||old?.mime||'',size:d.size||old?.size||0,importedAt:old?.importedAt||Date.now(),lastOpened:Date.now(),recent:true,favorite:old?.favorite||false,page:old?.page||1,pages:old?.pages||1,progress:old?.progress||0,section:'Imported document'};imported=imported.filter(x=>x!==old);imported.unshift(n);write(K.docs,imported);renderImported();openReader(n.name);toast(`${n.name} wurde zur Library hinzugefügt.`)}

let noteStore=read(K.notes,[]),noteId=null;
function renderNotes(){const l=document.getElementById('lumaNotesList');if(!l)return;l.innerHTML=noteStore.map(n=>`<button class="luma-note-item ${n.id===noteId?'selected':''}" data-n="${n.id}"><strong>${esc(n.title)}</strong><small>${esc(n.date)}</small></button>`).join('')||'<div class="luma-card"><strong>Noch keine LuMa Notes</strong><small>Mit „Neue Notiz“ startest du.</small></div>';document.querySelectorAll('[data-n]').forEach(b=>b.addEventListener('click',()=>loadNote(b.dataset.n)))}
function loadNote(id){const n=noteStore.find(x=>x.id===id);if(!n)return;noteId=id;const t=document.getElementById('noteTitle'),d=document.getElementById('noteDate'),e=document.getElementById('lumaNoteEditor');if(t)t.value=n.title;if(d)d.textContent=n.date;if(e)e.value=n.body||'';renderNotes()}
function newNote(){const n={id:`n-${Date.now()}`,title:'Neue Notiz',body:'',date:new Date().toLocaleDateString('de-CH'),updatedAt:Date.now()};noteStore.unshift(n);noteId=n.id;write(K.notes,noteStore);renderNotes();loadNote(n.id);go('notes')}
function saveNote(){if(!noteId)return;const n=noteStore.find(x=>x.id===noteId);if(!n)return;n.title=document.getElementById('noteTitle')?.value||n.title;n.body=document.getElementById('lumaNoteEditor')?.value||'';n.updatedAt=Date.now();write(K.notes,noteStore)}
document.getElementById('newNote')?.addEventListener('click',newNote);

const projects=[...document.querySelectorAll('.project-card')];projects.forEach(c=>c.addEventListener('click',()=>{projects.forEach(x=>x.classList.toggle('selected',x===c));const q=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};q('projectTitle',c.dataset.project);q('projectProgress',`${c.dataset.progress}%`);q('projectTasks',c.dataset.tasks);const b=document.getElementById('projectProgressBar');if(b)b.style.width=`${c.dataset.progress}%`}));
document.querySelectorAll('[data-work-tab]').forEach(b=>b.addEventListener('click',()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));

let aiContext='general';const modes=[...document.querySelectorAll('.mode-switch button')];modes.forEach(b=>b.addEventListener('click',()=>{modes.forEach(x=>x.classList.remove('selected'));b.classList.add('selected');localStorage.setItem('luma.ai.mode',b.textContent.trim())}));
function aiCtx(c){aiContext=c;const labels={general:'General workspace',reader:`Document: ${activeDoc}`,project:`Project: ${document.getElementById('projectTitle')?.textContent||'Active project'}`,notes:`Note: ${document.getElementById('noteTitle')?.value||'Selected note'}`},e=document.getElementById('aiContextLabel');if(e)e.textContent=`Context: ${labels[c]}`;document.querySelectorAll('[data-ai-context]').forEach(b=>b.classList.toggle('selected',b.dataset.aiContext===c))}
document.querySelectorAll('[data-ai-context]').forEach(b=>b.addEventListener('click',()=>aiCtx(b.dataset.aiContext)));document.querySelectorAll('.ask-ai').forEach(b=>b.addEventListener('click',()=>{aiCtx(b.dataset.context||'general');go('ai')}));
function msg(role,text){const c=document.getElementById('chatCard');if(!c)return;const e=document.createElement('div');e.className=`message ${role}`;e.innerHTML=`<p>${esc(text)}</p>`;c.appendChild(e);const h=read(K.chat,[]);h.push({role,text,context:aiContext,ts:Date.now()});write(K.chat,h.slice(-60))}
function sendAi(t){const i=document.getElementById('aiInput'),v=(t||i?.value||'').trim();if(!v)return;msg('user',v);const mode=document.querySelector('.mode-switch button.selected')?.textContent.trim()||'Online',ctx={general:'LuMa Workspace',reader:`Dokument „${activeDoc}“`,project:`Projekt „${document.getElementById('projectTitle')?.textContent||''}“`,notes:`Notiz „${document.getElementById('noteTitle')?.value||''}“`}[aiContext];msg('assistant',`${mode}-Modus · Kontext ${ctx}. Anfrage und Kontext sind im Workspace gespeichert; das produktive LuMa-AI-Backend wird separat angebunden.`);if(i)i.value=''}
document.getElementById('aiSend')?.addEventListener('click',()=>sendAi());document.getElementById('aiInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')sendAi()});document.querySelectorAll('.ai-suggestions button').forEach(b=>b.addEventListener('click',()=>sendAi(b.textContent)));

function ensureBlocks(){const lib=document.querySelector('[data-screen="library"]');if(lib&&!document.getElementById('libraryProBar')){const b=document.createElement('div');b.id='libraryProBar';b.className='luma-blockbar';b.innerHTML='<button class="luma-btn primary" id="libImport">Dokument importieren</button><button class="luma-btn" id="libResume">Weiterlesen</button>';lib.querySelector('.library-toolbar')?.insertAdjacentElement('afterend',b);document.getElementById('libImport')?.addEventListener('click',pick);document.getElementById('libResume')?.addEventListener('click',()=>{const d=[...imported].sort((a,b)=>(b.lastOpened||0)-(a.lastOpened||0))[0];openReader(d?.name||activeDoc)})}
const r=document.querySelector('[data-screen="reader"]');if(r&&!document.getElementById('readerProBar')){const b=document.createElement('div');b.id='readerProBar';b.className='luma-blockbar';b.innerHTML='<button class="luma-btn primary" id="readerImport">PDF / EPUB importieren</button><button class="luma-btn" id="readerAI">Seite an LuMa AI</button>';r.querySelector('.reader-toolbar')?.insertAdjacentElement('afterend',b);const c=document.createElement('div');c.className='luma-card';c.innerHTML='<strong>Reader Pro 0.9</strong><small>Lesestand, Bookmarks und importierte Dokumente werden dauerhaft lokal gespeichert. Native PDF-Seitenrendering folgt als eigener Reader-/Shell-Schritt.</small>';b.insertAdjacentElement('afterend',c);document.getElementById('readerImport')?.addEventListener('click',pick);document.getElementById('readerAI')?.addEventListener('click',()=>{aiCtx('reader');go('ai')})}
const n=document.querySelector('[data-screen="notes"]');if(n&&!document.getElementById('lumaNoteEditor')){const b=document.createElement('section');b.innerHTML='<div class="luma-card"><strong>Notes Pro 0.9 · Autosave</strong><small>Lokale, persistente Textnotizen mit direktem LuMa-AI-Kontext.</small></div><div id="lumaNotesList" class="luma-notes-list"></div><textarea id="lumaNoteEditor" class="luma-note-editor" placeholder="Notiz schreiben …"></textarea><div class="luma-blockbar"><button class="luma-btn primary" id="saveNote">Speichern</button><button class="luma-btn" id="noteAI">Mit LuMa AI öffnen</button></div>';n.appendChild(b);renderNotes();document.getElementById('saveNote')?.addEventListener('click',()=>{saveNote();toast('Notiz gespeichert.')});document.getElementById('noteAI')?.addEventListener('click',()=>{saveNote();aiCtx('notes');go('ai')});document.getElementById('lumaNoteEditor')?.addEventListener('input',()=>{clearTimeout(window.__ns);window.__ns=setTimeout(saveNote,450)});document.getElementById('noteTitle')?.addEventListener('input',()=>{clearTimeout(window.__nt);window.__nt=setTimeout(saveNote,450)});if(noteStore[0])loadNote(noteStore[0].id)}
const a=document.querySelector('[data-screen="ai"]');if(a&&!document.getElementById('aiWorkspaceCard')){const b=document.createElement('div');b.id='aiWorkspaceCard';b.className='luma-card';b.innerHTML='<strong>LuMa AI Workspace 0.9</strong><small>Lokaler Session-Verlauf · Kontext aus Reader, Work und Notes · Online/Local/Offline-Modus vorbereitet.</small>';a.querySelector('.mode-switch')?.insertAdjacentElement('afterend',b);const sm=localStorage.getItem('luma.ai.mode');if(sm)modes.forEach(x=>x.classList.toggle('selected',x.textContent.trim()===sm))}}

function diagnostics(){if(document.querySelector('[data-screen="diagnostics"]'))return;const main=document.querySelector('main.content');if(!main)return;const s=document.createElement('section');s.className='screen';s.dataset.screen='diagnostics';s.innerHTML='<div class="diag-wrap"><div class="section-head"><div><span class="eyebrow">LUMA SLATE SYSTEM</span><h1>Diagnostics</h1></div><button class="toolbar-button" id="diagBack">‹ Home</button></div><div class="diag-grid"><div class="diag"><span>SHELL</span><strong id="dShell">—</strong></div><div class="diag"><span>UI</span><strong id="dUi">—</strong></div><div class="diag"><span>BATTERY</span><strong id="dBat">—</strong></div><div class="diag"><span>STORAGE</span><strong id="dStore">—</strong></div><div class="diag"><span>NETWORK</span><strong id="dNet">—</strong></div><div class="diag"><span>UPDATE</span><strong id="dUpd">—</strong></div></div><div class="luma-blockbar"><button class="luma-btn primary" id="dCheck">Nach Updates suchen</button><button class="luma-btn" id="dPick">Dokument importieren</button></div></div>';main.appendChild(s);document.getElementById('diagBack')?.addEventListener('click',()=>go('home'));document.getElementById('dCheck')?.addEventListener('click',()=>window.LuMaNative?.checkForUpdates?.());document.getElementById('dPick')?.addEventListener('click',pick);const tools=[...document.querySelectorAll('.tile')].find(t=>t.querySelector('strong')?.textContent.trim()==='TOOLS');if(tools)tools.addEventListener('click',()=>{refresh();go('diagnostics')});const f=[...document.querySelectorAll('.quick-grid button')].find(b=>b.querySelector('span')?.textContent.trim()==='Files');f?.addEventListener('click',pick)}
function refresh(){const s=parseNative('getSystemInfo'),u=parseNative('getUpdateStatus'),set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('dShell',nativeVer('getShellVersion',LUMA_SHELL_VERSION));set('dUi',nativeVer('getUiVersion',LUMA_UI_VERSION));set('dBat',Number.isFinite(s.batteryPercent)?`${s.batteryPercent}%${s.charging?' · charging':''}`:'—');set('dStore',s.storageFreeBytes?fmt(s.storageFreeBytes):'—');set('dNet',s.networkType||'—');set('dUpd',u.status||'idle');const st=[...document.querySelectorAll('.topbar .status span')];if(st[0]&&s.networkType)st[0].textContent=s.networkType;if(st[1]&&Number.isFinite(s.batteryPercent))st[1].textContent=`${s.batteryPercent}%`;badge()}
window.addEventListener('luma-file-selected',e=>importDoc(e.detail||{}));window.addEventListener('luma-update-status',e=>{const s=e.detail?.status||'unknown';toast({up_to_date:'LuMa Slate ist aktuell.',checking:'Update wird geprüft.',downloading:'Update wird geladen.',updated:'Update installiert.',shell_required:'Neue Shell-Version erforderlich.'}[s]||`Update: ${s}`);refresh()});window.addEventListener('luma-update-error',()=>toast('Update konnte nicht geladen werden.'));

brand();diagnostics();ensureBlocks();renderImported();renderLibrary();refresh();setTimeout(refresh,1200);setInterval(refresh,60000);if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
