(()=>{
'use strict';
const V='0.10.0';
const LS={annotations:'luma.annotations.v1',sync:'luma.sync.v1',linear:'luma.linear.snapshot.v1'};
const rd=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const wr=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const say=t=>{if(typeof toast==='function')toast(t);};

function injectCss(){if(document.getElementById('luma-v010-css'))return;const s=document.createElement('style');s.id='luma-v010-css';s.textContent=`
.pdf-native-page{position:relative!important;padding:0!important;overflow:auto!important;background:#dfe5e3!important;display:flex;justify-content:center;align-items:flex-start;min-height:760px}.pdf-stage{position:relative;display:inline-block;margin:18px auto;background:#fff;border:2px solid #071117;box-shadow:none}.pdf-stage img{display:block;max-width:none;user-select:none;-webkit-user-drag:none}.pdf-ink{position:absolute;inset:0;width:100%;height:100%;touch-action:none;pointer-events:none}.pdf-ink.active{pointer-events:auto}.reader-native-status{display:flex;gap:8px;align-items:center;flex-wrap:wrap;padding:9px 12px;border:2px solid #8f9b99;background:#fff;border-radius:9px;margin:10px 0;font-size:12px;font-weight:800}.reader-native-status b{color:#07565b}.annot-actions{display:flex;gap:8px;margin:8px 0}.annot-actions button{min-height:46px;border:2px solid #071117;background:#fff;border-radius:9px;padding:8px 12px;font-weight:800}.work-pro-linear{margin-top:16px;border:2px solid #071117;background:#fff;border-radius:12px;padding:16px}.linear-head{display:flex;justify-content:space-between;align-items:center;gap:10px;border-bottom:2px solid #8f9b99;padding-bottom:12px}.linear-head h3{margin:3px 0 0;font-size:24px}.linear-list{display:grid;gap:8px;margin-top:12px}.linear-issue{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px;border:2px solid #8f9b99;background:#fff;border-radius:9px;padding:11px;text-align:left}.linear-key{font-weight:900;color:#07565b}.linear-copy strong,.linear-copy small{display:block}.linear-copy small{margin-top:3px;color:#39484a}.linear-open{min-height:42px;min-width:52px;border:2px solid #071117;background:#071117;color:#fff;border-radius:8px;font-weight:900}.sync-panel-v010{margin-top:14px;border:2px solid #071117;background:#fff;border-radius:12px;padding:15px}.sync-panel-v010 header{display:flex;justify-content:space-between;gap:10px;align-items:center}.sync-state{font-weight:900;color:#07565b}.sync-meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.sync-meta div{border:2px solid #8f9b99;padding:10px;border-radius:8px}.sync-meta span,.sync-meta strong{display:block}.sync-meta span{font-size:11px;font-weight:800;color:#39484a}.sync-meta strong{margin-top:4px}.v010-pill{display:inline-block;border:2px solid #07565b;padding:4px 7px;border-radius:99px;font-size:11px;font-weight:900;color:#07565b}.pdf-error{padding:30px;text-align:center}.pdf-error strong,.pdf-error small{display:block}.pdf-error small{margin-top:8px;color:#39484a}@media(max-width:720px){.linear-issue{grid-template-columns:auto 1fr auto}.pdf-stage{margin:10px auto}.sync-meta{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(s)}

let pdf={uri:'',name:'',pages:0,zoom:1};
function importedDocs(){try{return JSON.parse(localStorage.getItem('luma.docs.v1')||'[]')}catch{return []}}
function saveImported(list){wr('luma.docs.v1',list)}
function activeReaderName(){return document.getElementById('readerDocTitle')?.textContent?.trim()||''}
function selectedPdf(){const name=activeReaderName();return importedDocs().find(d=>d.name===name&&(d.mime||'').toLowerCase().includes('pdf'))||null}
function pdfInfo(uri){try{return JSON.parse(window.LuMaNative?.getPdfInfo?.(uri)||'{}')}catch{return {}}}
function nativeRender(uri,p,maxWidth){try{return JSON.parse(window.LuMaNative?.renderPdfPage?.(uri,p,maxWidth)||'{}')}catch(e){return {error:String(e)}}}
function updatePdfMetadata(doc,info){if(!doc||!info.pageCount)return;const list=importedDocs(),x=list.find(d=>d.uri===doc.uri||d.name===doc.name);if(x){x.pages=info.pageCount;x.page=Math.min(Math.max(1,x.page||1),info.pageCount);x.progress=Math.round((x.page/info.pageCount)*100);saveImported(list)}const el=document.getElementById('readerPages');if(el)el.textContent=info.pageCount}
function attachReaderStatus(){const r=document.querySelector('[data-screen="reader"]');if(!r||document.getElementById('readerNativeStatus'))return;const e=document.createElement('div');e.id='readerNativeStatus';e.className='reader-native-status';e.innerHTML=`<span class="v010-pill">READER PRO ${V}</span><span id="pdfStatus">Native PDF bereit</span><b id="pdfZoom">100%</b>`;document.getElementById('readerProBar')?.insertAdjacentElement('afterend',e);const a=document.createElement('div');a.className='annot-actions';a.innerHTML='<button id="pdfZoomOut">− Zoom</button><button id="pdfZoomIn">＋ Zoom</button><button id="inkUndo">↶ Undo</button><button id="inkClear">Clear Ink</button>';e.insertAdjacentElement('afterend',a);document.getElementById('pdfZoomOut')?.addEventListener('click',()=>setZoom(pdf.zoom-.1));document.getElementById('pdfZoomIn')?.addEventListener('click',()=>setZoom(pdf.zoom+.1));document.getElementById('inkUndo')?.addEventListener('click',undoInk);document.getElementById('inkClear')?.addEventListener('click',clearInk)}
function setZoom(z){pdf.zoom=Math.min(1.8,Math.max(.65,Math.round(z*10)/10));const stage=document.querySelector('.pdf-stage'),img=document.querySelector('.pdf-stage img');if(stage&&img){const w=Number(img.dataset.baseWidth||img.naturalWidth||1000)*pdf.zoom;img.style.width=`${w}px`;stage.style.width=`${w}px`;stage.style.height='auto';resizeInk()}const e=document.getElementById('pdfZoom');if(e)e.textContent=`${Math.round(pdf.zoom*100)}%`}
function renderPdf(doc){if(!doc?.uri||!window.LuMaNative?.renderPdfPage)return;pdf.uri=doc.uri;pdf.name=doc.name;const info=pdfInfo(doc.uri);if(info.error){showPdfError(info.error);return}pdf.pages=info.pageCount||1;updatePdfMetadata(doc,info);let p=Math.max(1,Number(document.getElementById('readerPage')?.textContent)||doc.page||1);p=Math.min(p,pdf.pages);const pe=document.getElementById('readerPage');if(pe)pe.textContent=p;const status=document.getElementById('pdfStatus');if(status)status.textContent=`Native PDF · ${pdf.pages} Seiten`;requestAnimationFrame(()=>{const out=nativeRender(doc.uri,p-1,1400);if(!out.base64){showPdfError(out.error||'PDF-Seite konnte nicht gerendert werden.');return}const host=document.querySelector('.paper-page');if(!host)return;host.classList.add('pdf-native-page');host.innerHTML=`<div class="pdf-stage"><img alt="${safe(doc.name)} – Seite ${p}" data-base-width="${out.width}" width="${out.width}" height="${out.height}" src="data:image/png;base64,${out.base64}"><canvas class="pdf-ink" aria-label="Annotation layer"></canvas></div>`;const img=host.querySelector('img');img.addEventListener('load',()=>{setZoom(pdf.zoom);setupInk();loadInk()},{once:true});const list=importedDocs(),x=list.find(d=>d.uri===doc.uri||d.name===doc.name);if(x){x.page=p;x.pages=pdf.pages;x.progress=Math.round(p/pdf.pages*100);x.lastOpened=Date.now();saveImported(list)}})}
function showPdfError(err){const host=document.querySelector('.paper-page');if(host)host.innerHTML=`<div class="pdf-error"><strong>PDF konnte nicht dargestellt werden.</strong><small>${safe(err)}</small></div>`}
function renderActivePdf(){const d=selectedPdf();if(d)renderPdf(d)}
function bindReader(){attachReaderStatus();['readerPrev','readerNext'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>setTimeout(renderActivePdf,40)));const title=document.getElementById('readerDocTitle');if(title)new MutationObserver(()=>setTimeout(renderActivePdf,60)).observe(title,{childList:true,characterData:true,subtree:true});window.addEventListener('luma-file-selected',e=>{const d=e.detail||{};if((d.mime||'').toLowerCase().includes('pdf'))setTimeout(renderActivePdf,120)});document.querySelectorAll('[data-reader-tool="pen"],[data-reader-tool="highlight"]').forEach(b=>b.addEventListener('click',()=>setTimeout(updateInkMode,0)))}

function annKey(){const p=Number(document.getElementById('readerPage')?.textContent)||1;return `${pdf.uri}::${p}`}
function allAnn(){return rd(LS.annotations,{})}
function currentStrokes(){return allAnn()[annKey()]||[]}
function putStrokes(strokes){const all=allAnn();all[annKey()]=strokes;wr(LS.annotations,all);markSyncDirty('annotations')}
function setupInk(){const c=document.querySelector('.pdf-ink');if(!c)return;resizeInk();let drawing=false,stroke=null;c.onpointerdown=e=>{const tool=activeTool();if(!tool)return;drawing=true;c.setPointerCapture?.(e.pointerId);const r=c.getBoundingClientRect();stroke={tool,points:[[(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]]};e.preventDefault()};c.onpointermove=e=>{if(!drawing||!stroke)return;const r=c.getBoundingClientRect();stroke.points.push([(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]);drawAll([...currentStrokes(),stroke]);e.preventDefault()};c.onpointerup=e=>{if(!drawing||!stroke)return;drawing=false;const s=currentStrokes();s.push(stroke);putStrokes(s);drawAll(s);stroke=null;e.preventDefault()};updateInkMode()}
function activeTool(){if(document.querySelector('[data-reader-tool="pen"]')?.classList.contains('selected'))return 'pen';if(document.querySelector('[data-reader-tool="highlight"]')?.classList.contains('selected'))return 'highlight';return ''}
function updateInkMode(){document.querySelector('.pdf-ink')?.classList.toggle('active',!!activeTool())}
function resizeInk(){const c=document.querySelector('.pdf-ink'),stage=document.querySelector('.pdf-stage');if(!c||!stage)return;const r=stage.getBoundingClientRect(),ratio=Math.min(2,window.devicePixelRatio||1);c.width=Math.max(1,Math.round(r.width*ratio));c.height=Math.max(1,Math.round(r.height*ratio));c.style.width=`${r.width}px`;c.style.height=`${r.height}px`;drawAll(currentStrokes())}
function drawAll(strokes){const c=document.querySelector('.pdf-ink');if(!c)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);for(const s of strokes){if(!s.points?.length)continue;ctx.beginPath();ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle=s.tool==='highlight'?'rgba(7,86,91,.32)':'rgba(7,17,23,.92)';ctx.lineWidth=s.tool==='highlight'?Math.max(16,c.width*.012):Math.max(3,c.width*.0025);s.points.forEach((pt,i)=>{const x=pt[0]*c.width,y=pt[1]*c.height;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}}
function loadInk(){drawAll(currentStrokes());updateInkMode()}
function undoInk(){const s=currentStrokes();s.pop();putStrokes(s);drawAll(s)}
function clearInk(){putStrokes([]);drawAll([]);say('Annotationen dieser Seite gelöscht.')}

const LINEAR=[
{id:'NEX-84',title:'Reader Pro – PDF, Annotation, Pen & AI Context',status:'Backlog',priority:'High',url:'https://linear.app/nexi86/issue/NEX-84/reader-pro-pdf-annotation-pen-and-ai-context'},
{id:'NEX-89',title:'Sync Engine – LuisServer, Offline Cache & Device Sync',status:'Backlog',priority:'High',url:'https://linear.app/nexi86/issue/NEX-89/sync-engine-luisserver-offline-cache-and-device-sync'},
{id:'NEX-86',title:'Work – Projekte, Tasks, BIM & BOG Fusion Context',status:'Backlog',priority:'Medium',url:'https://linear.app/nexi86/issue/NEX-86/work-projekte-tasks-bim-and-bog-fusion-context'},
{id:'NEX-85',title:'Library Pro – Dokumentindex, Suche & Reading State',status:'Backlog',priority:'High',url:'https://linear.app/nexi86/issue/NEX-85/library-pro-dokumentindex-suche-and-reading-state'},
{id:'NEX-87',title:'LuMa AI Workspace – Online, Local, Offline & Context',status:'Backlog',priority:'High',url:'https://linear.app/nexi86/issue/NEX-87/luma-ai-workspace-online-local-offline-and-context'},
{id:'NEX-88',title:'Notes Pro – Handschrift, Pen Tools & AI Meeting Notes',status:'Backlog',priority:'Medium',url:'https://linear.app/nexi86/issue/NEX-88/notes-pro-handschrift-pen-tools-and-ai-meeting-notes'}
];
function openExternal(url){if(window.LuMaNative?.openExternalUrl)window.LuMaNative.openExternalUrl(url);else window.open(url,'_blank')}
function workPro(){const w=document.querySelector('[data-screen="work"]');if(!w||document.getElementById('workLinear'))return;const box=document.createElement('section');box.id='workLinear';box.className='work-pro-linear';box.innerHTML=`<div class="linear-head"><div><span class="eyebrow">WORK PRO · CONNECTED TASKS</span><h3>Linear · LuMa Slate</h3></div><button class="luma-btn primary" id="linearRefresh">Refresh</button></div><div class="linear-list">${LINEAR.map(i=>`<div class="linear-issue"><span class="linear-key">${i.id}</span><div class="linear-copy"><strong>${safe(i.title)}</strong><small>${i.status} · ${i.priority}</small></div><button class="linear-open" data-linear="${safe(i.url)}">↗</button></div>`).join('')}</div><div class="luma-card"><strong>Linear Integration Foundation</strong><small>Aktuelle Projekt-Issues sind direkt aus Work erreichbar. Schreibzugriff und Live-Synchronisierung werden sicher über den LuMa-Backend-Connector angebunden – kein Linear-Token wird auf dem BOOX gespeichert.</small></div>`;w.appendChild(box);box.querySelectorAll('[data-linear]').forEach(b=>b.addEventListener('click',()=>openExternal(b.dataset.linear)));document.getElementById('linearRefresh')?.addEventListener('click',()=>{wr(LS.linear,{issues:LINEAR,snapshotAt:Date.now()});say('Linear-Snapshot aktualisiert. Live-Connector ist vorbereitet.')})}

function syncState(){return rd(LS.sync,{dirty:true,lastLocal:0,lastRemote:0,queue:[]})}
function markSyncDirty(type){const s=syncState();s.dirty=true;s.queue=[...(s.queue||[]),{type,ts:Date.now()}].slice(-100);wr(LS.sync,s);renderSync()}
function snapshot(){const keys=['luma.docs.v1','luma.reader.v1','luma.notes.v1','luma.chat.v1',LS.annotations];const data={version:1,device:'LuMa Slate',createdAt:new Date().toISOString(),payload:{}};keys.forEach(k=>data.payload[k]=localStorage.getItem(k));return data}
async function runSync(){const s=syncState(),endpoint=localStorage.getItem('luma.sync.endpoint')||'';s.lastLocal=Date.now();s.dirty=false;wr('luma.sync.snapshot.v1',snapshot());if(endpoint){try{const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(snapshot())});if(!r.ok)throw new Error(`HTTP ${r.status}`);s.lastRemote=Date.now();s.queue=[];say('LuMa Sync mit Remote-Endpunkt abgeschlossen.')}catch(e){s.dirty=true;s.queue=[...(s.queue||[]),{type:'sync-error',ts:Date.now()}].slice(-100);say('Remote Sync nicht erreichbar – Änderungen bleiben sicher lokal.')}}else{say('Lokaler Sync-Snapshot erstellt. LuisServer-Endpunkt folgt als nächster Backend-Schritt.')}wr(LS.sync,s);renderSync()}
function renderSync(){const s=syncState(),state=document.getElementById('syncStateV010'),last=document.getElementById('syncLastV010'),queue=document.getElementById('syncQueueV010');if(state)state.textContent=s.dirty?'Änderungen ausstehend':'Lokal gesichert';if(last)last.textContent=s.lastRemote?new Date(s.lastRemote).toLocaleString('de-CH'):s.lastLocal?new Date(s.lastLocal).toLocaleString('de-CH'):'Noch nie';if(queue)queue.textContent=String((s.queue||[]).length)}
function syncPro(){const home=document.querySelector('[data-screen="home"]');if(!home||document.getElementById('syncPanelV010'))return;const p=document.createElement('section');p.id='syncPanelV010';p.className='sync-panel-v010';p.innerHTML=`<header><div><span class="eyebrow">LUMA SYNC ENGINE</span><strong>Local-first Device State</strong></div><span class="sync-state" id="syncStateV010">—</span></header><div class="sync-meta"><div><span>LAST SYNC</span><strong id="syncLastV010">—</strong></div><div><span>QUEUE</span><strong id="syncQueueV010">0</strong></div></div><div class="luma-blockbar"><button class="luma-btn primary" id="syncNowV010">Jetzt synchronisieren</button><button class="luma-btn" id="syncServerV010">LuisServer vorbereiten</button></div>`;const panels=home.querySelectorAll('.panel');(panels[panels.length-1]||home).insertAdjacentElement('afterend',p);document.getElementById('syncNowV010')?.addEventListener('click',runSync);document.getElementById('syncServerV010')?.addEventListener('click',()=>say('Sync-Engine ist bereit. Für LuisServer fehlt nur noch der authentifizierte LuMa-Sync-Endpunkt.'));const syncTile=[...document.querySelectorAll('.tile')].find(t=>t.querySelector('strong')?.textContent.trim()==='SYNC');syncTile?.addEventListener('click',runSync);const libSync=[...document.querySelectorAll('.library-sync-card button')][0];libSync?.addEventListener('click',runSync);['luma.docs.v1','luma.reader.v1','luma.notes.v1'].forEach(k=>window.addEventListener('storage',e=>{if(e.key===k)markSyncDirty(k)}));renderSync()}

function boot(){injectCss();bindReader();workPro();syncPro();wr(LS.linear,{issues:LINEAR,snapshotAt:Date.now()});setTimeout(renderActivePdf,300);window.addEventListener('resize',()=>setTimeout(resizeInk,100));console.info(`LuMa Slate feature blocks ${V} ready`)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
